"""Python executor tool — V5.1 sandboxed subprocess runner.

Runs Python code generated by the LLM (or pasted by the user) in
an isolated subprocess with strict limits. Used by the V5.1 tool
router when the user's question involves computation, plotting,
or code execution.

Sandbox model
-------------
We use ``subprocess.run`` instead of ``exec()`` because :
1. A separate process protects the main Lythéa server from RuntimeError
   /memory leaks / infinite loops (we can ``kill -9`` after timeout).
2. A clean ``cwd`` (temp dir) limits filesystem damage scope — code
   can read/write inside its temp dir but not the project root.
3. A pruned ``env`` removes secrets that might be in the main env.

What this does NOT protect against
----------------------------------
- ``os.system("rm -rf $HOME")`` — the subprocess inherits the user's
  filesystem permissions, so it can wipe ``/home/user``. For real
  multi-user / untrusted code, use Docker or nsjail. Acceptable for
  a local single-user setup where you'd type the same commands yourself.
- Network egress — the subprocess can hit the internet. If you want
  network isolation, run Lythéa inside a Docker container with
  ``--network none``.
- Slow exfiltration via DNS — same as above.

For Mika's solo local usage, ``subprocess + timeout + clean cwd``
is the right trade-off. Document the limit ; tighten with Docker
if Lythéa ever serves external users.

API
---
``run(code, timeout=5.0, allow_plots=True)`` → dict :
    {
        "ok": bool,
        "stdout": str,        # captured stdout
        "stderr": str,        # captured stderr
        "result": str,        # last expression value if any
        "duration_ms": int,
        "plots": list[str],   # base64 PNG of any plt.show() calls
        "error": str | None,  # only set if ok=False
    }
"""

from __future__ import annotations

import base64
import logging
import os
import re
import shutil
import subprocess
import sys
import tempfile
import time
from pathlib import Path

log = logging.getLogger("lythea.tools.python_executor")


# ── Configuration ─────────────────────────────────────────────────────

DEFAULT_TIMEOUT_S = 5.0
MAX_TIMEOUT_S = 30.0
MAX_OUTPUT_BYTES = 64 * 1024  # 64 KB stdout/stderr cap

# Modules autorisés à l'import (en plus de la stdlib). Si la liste est
# vide, on n'impose aucune restriction (mode "tout passe"). Tu peux
# durcir en listant explicitement les modules safe (math, statistics,
# numpy, pandas, matplotlib, ...) et en empêchant les autres via un
# wrapper sur __import__. Pour l'instant on laisse ouvert.
ALLOWED_EXTRA_MODULES: tuple[str, ...] = ()


# ── V5.9.0 — Auto-install whitelist ───────────────────────────────────
#
# Quand le sandbox crash avec ModuleNotFoundError, on tente une auto-
# installation via pip — MAIS uniquement pour les libs scientifiques
# courantes whitelisted. Cela évite :
#   1. Les attaques de prompt injection ("installe `requests` et fetch X")
#   2. Le typosquatting (lib avec nom proche d'une lib légitime)
#   3. L'inflation incontrôlée du sandbox avec n'importe quoi
#
# Le mapping va du nom d'import (gauche, ce que voit le ModuleNotFoundError)
# vers le nom pip (droite, ce qu'on passe à `pip install`). Ils sont
# souvent identiques mais pas toujours (ex: sklearn → scikit-learn).
#
# Pour ajouter une lib : édite cette table. PAS de pip install arbitraire
# basé sur un nom extrait du stderr — toujours via cette whitelist.
AUTO_INSTALL_WHITELIST: dict[str, str] = {
    # Maths & calcul scientifique
    "numpy": "numpy",
    "scipy": "scipy",
    "sympy": "sympy",
    "mpmath": "mpmath",
    # Stats & ML
    "pandas": "pandas",
    "sklearn": "scikit-learn",
    "statsmodels": "statsmodels",
    "xgboost": "xgboost",
    "lightgbm": "lightgbm",
    # Visualisation
    "matplotlib": "matplotlib",
    "seaborn": "seaborn",
    "plotly": "plotly",
    "bokeh": "bokeh",
    # Manipulation données
    "openpyxl": "openpyxl",
    "xlsxwriter": "xlsxwriter",
    "tabulate": "tabulate",
    # Texte & encodages
    "regex": "regex",
    "unidecode": "unidecode",
    "chardet": "chardet",
    "ftfy": "ftfy",
    # Sciences spécifiques (chimiométrie / spectroscopie — Mika's domain)
    "scikit-image": "scikit-image",
    "skimage": "scikit-image",
    "PIL": "Pillow",
    "Pillow": "Pillow",
    # Dates & temps
    "dateutil": "python-dateutil",
    "pytz": "pytz",
    "arrow": "arrow",
    # Sérialisation
    "yaml": "PyYAML",
    "toml": "toml",
    "msgpack": "msgpack",
    # Stat avancée et chimie
    "pingouin": "pingouin",
    "rdkit": "rdkit",
}

# Cap dur sur les auto-installs par tour (anti boucle infinie)
MAX_AUTO_INSTALLS_PER_RUN = 3
# Timeout pour pip install (matplotlib + deps = ~30s sur RunPod)
AUTO_INSTALL_TIMEOUT_S = 90.0


# Détecteur de ModuleNotFoundError dans le stderr
_MODULE_NOT_FOUND_RE = re.compile(
    r"ModuleNotFoundError:\s*No module named\s*['\"]([\w\.]+)['\"]"
)


def _extract_missing_module(stderr: str) -> str | None:
    """Extrait le nom du module manquant depuis un stderr Python.

    Retourne le nom du **package root** (avant le premier `.`) pour
    matcher la whitelist : "PIL.Image" → "PIL", "matplotlib.pyplot"
    → "matplotlib".

    Args:
        stderr: contenu stderr du subprocess Python

    Returns:
        Nom du module ou None si aucun ModuleNotFoundError détecté.
    """
    if not stderr:
        return None
    m = _MODULE_NOT_FOUND_RE.search(stderr)
    if not m:
        return None
    full = m.group(1)
    # Package root pour matcher la whitelist
    return full.split(".")[0]


def _pip_install(package: str, timeout: float = AUTO_INSTALL_TIMEOUT_S) -> dict:
    """Tente d'installer un package via pip dans le Python qui fait
    tourner Lythéa. Retourne un dict de statut.

    SÉCURITÉ : le package DOIT être validé contre AUTO_INSTALL_WHITELIST
    avant d'appeler cette fonction. Cette fonction ne fait pas elle-même
    la validation, c'est la responsabilité de l'appelant.

    V5.9.0 — Stratégie 2-passes pour PEP 668 :
      1. Tente d'abord pip install standard
      2. Si "externally-managed-environment" → retry avec --user
      3. Si encore échec → retry avec --break-system-packages
    Cette cascade couvre tous les cas : Python système (Ubuntu 24
    avec PEP 668), conda, venv, et installations user-only.

    Args:
        package: nom pip du package
        timeout: timeout pip en secondes

    Returns:
        {"ok": bool, "stdout": str, "stderr": str, "duration_ms": int}
    """
    base_cmd = [
        sys.executable, "-m", "pip", "install",
        "--no-input",
        "--disable-pip-version-check",
        "--quiet",
    ]

    # 3 stratégies en cascade
    strategies = [
        ([], "standard"),
        (["--user"], "user-only"),
        (["--break-system-packages"], "break-system-packages"),
    ]

    t0 = time.monotonic()
    last_result = {"ok": False, "stdout": "", "stderr": "no attempt"}

    for extra_args, strategy_name in strategies:
        try:
            proc = subprocess.run(
                base_cmd + extra_args + [package],
                capture_output=True,
                text=True,
                timeout=timeout,
                check=False,
            )
            duration_ms = int((time.monotonic() - t0) * 1000)
            last_result = {
                "ok": proc.returncode == 0,
                "stdout": proc.stdout[:MAX_OUTPUT_BYTES] if proc.stdout else "",
                "stderr": proc.stderr[:MAX_OUTPUT_BYTES] if proc.stderr else "",
                "duration_ms": duration_ms,
                "returncode": proc.returncode,
                "strategy": strategy_name,
            }
            if last_result["ok"]:
                log.info(
                    "pip install %r succeeded via strategy=%r in %dms",
                    package, strategy_name, duration_ms,
                )
                return last_result
            # Si PEP 668, on retry avec la stratégie suivante
            stderr_lower = (last_result["stderr"] or "").lower()
            if "externally-managed-environment" in stderr_lower or \
               "break-system-packages" in stderr_lower:
                log.info(
                    "pip install %r : PEP 668 detected, trying next strategy",
                    package,
                )
                continue
            # Autre erreur → on n'insiste pas
            return last_result
        except subprocess.TimeoutExpired:
            duration_ms = int((time.monotonic() - t0) * 1000)
            log.warning("pip install timeout après %.1fs pour %r", timeout, package)
            return {
                "ok": False,
                "stdout": "",
                "stderr": f"Timeout après {timeout}s",
                "duration_ms": duration_ms,
                "returncode": -1,
                "strategy": strategy_name,
            }
        except Exception as exc:
            log.exception("pip install failed: %s", exc)
            last_result = {
                "ok": False,
                "stdout": "",
                "stderr": str(exc),
                "duration_ms": int((time.monotonic() - t0) * 1000),
                "returncode": -2,
                "strategy": strategy_name,
            }
            continue

    return last_result


# ── Code wrapper ───────────────────────────────────────────────────────


def _wrap_user_code(user_code: str, allow_plots: bool) -> str:
    """Wraps the user code so we can capture the last expression value
    and any matplotlib plots without modifying the user's logic.

    Strategy : append a preamble that configures matplotlib (Agg
    backend, no display), and a postamble that saves any pending
    figures to files in the cwd. The main runner picks them up.
    """
    preamble_lines = [
        "# === Lythéa python_executor preamble ===",
        "import sys, os, traceback",
    ]
    if allow_plots:
        preamble_lines.extend([
            "# Matplotlib in non-interactive mode so plt.show() doesn't",
            "# spawn a window. We save the figure list and serialise to",
            "# PNG at the end.",
            "try:",
            "    import matplotlib",
            "    matplotlib.use('Agg')",
            "    import matplotlib.pyplot as _lythea_plt",
            "except ImportError:",
            "    _lythea_plt = None",
        ])
    preamble_lines.append("# === User code starts ===")
    preamble = "\n".join(preamble_lines) + "\n"

    postamble_lines = [
        "",
        "# === Lythéa python_executor postamble ===",
    ]
    if allow_plots:
        postamble_lines.extend([
            "if _lythea_plt is not None:",
            "    _figs = [_lythea_plt.figure(n) for n in _lythea_plt.get_fignums()]",
            "    for _i, _fig in enumerate(_figs):",
            "        _fig.savefig(f'_lythea_plot_{_i}.png', dpi=100, bbox_inches='tight')",
            "        _lythea_plt.close(_fig)",
        ])
    postamble = "\n".join(postamble_lines) + "\n"

    return preamble + user_code + "\n" + postamble


# ── Main runner ────────────────────────────────────────────────────────


def run(
    code: str,
    timeout: float = DEFAULT_TIMEOUT_S,
    allow_plots: bool = True,
    cwd: str | None = None,
) -> dict:
    """Run Python code in a sandboxed subprocess.

    Parameters
    ----------
    code
        Raw Python source. Will be wrapped to capture plots and the
        last expression value.
    timeout
        Hard kill timeout in seconds. Capped at MAX_TIMEOUT_S.
    allow_plots
        If True, configures matplotlib to save plots as PNG files
        which we serialise to base64 and return.
    cwd
        Working directory. If None, we create a fresh temp dir and
        clean it up after. Pass a fixed dir if the caller wants to
        persist artifacts across calls (rare).

    Returns
    -------
    dict
        See module docstring for the schema. Always returns a dict ;
        never raises.
    """
    if not code or not code.strip():
        return {
            "ok": False,
            "stdout": "",
            "stderr": "",
            "result": "",
            "duration_ms": 0,
            "plots": [],
            "error": "empty_code",
        }

    timeout = min(max(0.5, timeout), MAX_TIMEOUT_S)

    owned_cwd = cwd is None
    if cwd is None:
        cwd = tempfile.mkdtemp(prefix="lythea_py_")

    wrapped = _wrap_user_code(code, allow_plots=allow_plots)
    script_path = Path(cwd) / "_lythea_user_script.py"
    script_path.write_text(wrapped, encoding="utf-8")

    # Clean env : keep only what's needed for Python to start.
    # V5.8.9 — Propagation élargie : on whitelist explicitement les
    # variables nécessaires pour que les libs Python soient trouvées
    # dans tous les environnements (système, venv, conda, user-site).
    #
    # Bug observé en V5.8.8 : matplotlib introuvable parce que clean_env
    # écrasait HOME → user-site (~/.local/...) inaccessible, et ne
    # propageait pas CONDA_PREFIX → conda env non activé dans subprocess.
    clean_env = {
        "PATH": os.environ.get("PATH", "/usr/local/bin:/usr/bin:/bin"),
        # V5.8.9 — HOME = vrai HOME, pas le tempdir.
        # Le user-site Python (~/.local/lib/python3.X/site-packages)
        # est calculé à partir de HOME. Sans ça, toute lib installée
        # via `pip install --user` est introuvable.
        # Pour rediriger les écritures, on utilise XDG_*_HOME pointant
        # vers cwd plutôt que d'écraser HOME complètement.
        "HOME": os.environ.get("HOME", cwd),
        "XDG_CACHE_HOME": str(Path(cwd) / "cache"),
        "XDG_CONFIG_HOME": str(Path(cwd) / "config"),
        "XDG_DATA_HOME": str(Path(cwd) / "data"),
        "PYTHONUNBUFFERED": "1",
        "PYTHONDONTWRITEBYTECODE": "1",
        "MPLBACKEND": "Agg",
        # Locale UTF-8 (cf V5.8.8)
        "LANG": "C.UTF-8",
        "LC_ALL": "C.UTF-8",
        "PYTHONIOENCODING": "utf-8",
    }
    # V5.8.9 — Propage les variables Python d'environnement.
    # Sans ces variables, conda/venv/poetry envs sont inopérants
    # dans le subprocess.
    for _var in (
        "PYTHONPATH",       # venvs custom, paths d'import
        "VIRTUAL_ENV",      # venv standard
        "CONDA_PREFIX",     # conda env activé
        "CONDA_DEFAULT_ENV",
        "CONDA_PYTHON_EXE",
        "POETRY_ACTIVE",    # poetry venv
        "PIPENV_ACTIVE",    # pipenv
        "USER", "LOGNAME",  # certaines libs en ont besoin
        "TMPDIR", "TMP", "TEMP",
        # CUDA pour torch/numpy GPU si jamais le code en a besoin
        "CUDA_HOME", "CUDA_PATH",
        "LD_LIBRARY_PATH",  # libs natives (matplotlib, scipy)
    ):
        if _var in os.environ:
            clean_env[_var] = os.environ[_var]

    # Crée les dirs XDG pour éviter les warnings au démarrage
    for _d in (clean_env["XDG_CACHE_HOME"], clean_env["XDG_CONFIG_HOME"],
               clean_env["XDG_DATA_HOME"]):
        try:
            Path(_d).mkdir(parents=True, exist_ok=True)
        except Exception:
            pass

    t0 = time.monotonic()
    try:
        proc = subprocess.run(
            [sys.executable, str(script_path)],
            capture_output=True,
            text=True,
            cwd=cwd,
            env=clean_env,
            timeout=timeout,
            check=False,
        )
        duration_ms = int((time.monotonic() - t0) * 1000)
        stdout = proc.stdout[:MAX_OUTPUT_BYTES] if proc.stdout else ""
        stderr = proc.stderr[:MAX_OUTPUT_BYTES] if proc.stderr else ""

        # Récolte des plots
        plots: list[str] = []
        if allow_plots:
            for plot_file in sorted(Path(cwd).glob("_lythea_plot_*.png")):
                try:
                    data = plot_file.read_bytes()
                    plots.append(base64.b64encode(data).decode("ascii"))
                except Exception as exc:
                    log.warning("Failed to read plot %s: %s", plot_file, exc)

        success = proc.returncode == 0
        return {
            "ok": success,
            "stdout": stdout,
            "stderr": stderr,
            "result": "",  # populated below for simple cases
            "duration_ms": duration_ms,
            "plots": plots,
            "returncode": proc.returncode,
            "error": None if success else f"exit_code_{proc.returncode}",
            # V5.9.0 — Champs pour le retry auto-install
            "installed_packages": [],  # libs installées pendant ce run
            "install_attempts": 0,
        }
    except subprocess.TimeoutExpired:
        duration_ms = int((time.monotonic() - t0) * 1000)
        log.warning("Python executor timeout after %.1fs", timeout)
        return {
            "ok": False,
            "stdout": "",
            "stderr": "",
            "result": "",
            "duration_ms": duration_ms,
            "plots": [],
            "error": f"timeout_{timeout}s",
            "installed_packages": [],
            "install_attempts": 0,
        }
    except Exception as exc:
        duration_ms = int((time.monotonic() - t0) * 1000)
        log.warning("Python executor crashed: %s", exc)
        return {
            "ok": False,
            "stdout": "",
            "stderr": "",
            "result": "",
            "duration_ms": duration_ms,
            "plots": [],
            "error": f"executor_crash: {exc}",
            "installed_packages": [],
            "install_attempts": 0,
        }
    finally:
        if owned_cwd:
            try:
                shutil.rmtree(cwd, ignore_errors=True)
            except Exception:
                pass


def run_with_auto_install(
    code: str,
    timeout: float = DEFAULT_TIMEOUT_S,
    allow_plots: bool = True,
    max_install_attempts: int = MAX_AUTO_INSTALLS_PER_RUN,
) -> dict:
    """V5.9.0 — Wrapper avec auto-install des libs scientifiques.

    Pipeline :
      1. Exécute le code via run()
      2. Si échec et stderr contient ModuleNotFoundError pour une lib
         whitelisted → pip install + retry
      3. Cap à max_install_attempts pour éviter boucles infinies
      4. Si lib non-whitelisted → on ne tente pas d'install, l'erreur
         remonte tel quel (sécurité : pas d'install arbitraire)

    Le résultat final contient ``installed_packages`` qui liste les
    libs qu'on a installées pendant ce run (vide si aucune install
    nécessaire). Permet à l'UI de signaler "🔧 matplotlib installé".

    Args:
        code: code Python à exécuter
        timeout: timeout par tentative d'exécution
        allow_plots: capturer les plots matplotlib
        max_install_attempts: nombre max d'auto-installs (anti boucle)

    Returns:
        Dict identique à run(), avec champs additionnels :
          - installed_packages: list[str] des libs installées
          - install_attempts: int, nombre d'auto-installs tentés
    """
    installed: list[str] = []
    last_attempted: set[str] = set()  # anti redondance dans même run

    for attempt in range(max_install_attempts + 1):
        result = run(code, timeout=timeout, allow_plots=allow_plots)
        # Inject le tracking dans le résultat
        result["installed_packages"] = list(installed)
        result["install_attempts"] = attempt

        if result.get("ok"):
            return result

        # Échec — voyons si c'est une ModuleNotFoundError résolvable
        missing = _extract_missing_module(result.get("stderr", ""))
        if not missing:
            # Pas un manque de module → erreur "vraie", on remonte
            return result

        if missing in last_attempted:
            # On a déjà tenté ce module dans ce run → boucle, on arrête
            log.warning(
                "Auto-install: %r already attempted in this run, "
                "giving up to avoid loop", missing,
            )
            return result

        if missing not in AUTO_INSTALL_WHITELIST:
            # Sécurité : on ne s'installe PAS n'importe quoi.
            log.info(
                "Auto-install refused: %r not in whitelist (security)",
                missing,
            )
            # On enrichit le stderr pour que le LLM sache quoi dire
            result["stderr"] = (
                result.get("stderr", "")
                + f"\n\n[Lythéa] Module '{missing}' demandé non disponible "
                f"et hors whitelist d'auto-install. "
                f"Modules auto-installables : "
                f"{', '.join(sorted(AUTO_INSTALL_WHITELIST.keys()))}"
            )
            return result

        if attempt >= max_install_attempts:
            log.warning(
                "Auto-install: max %d attempts reached, giving up",
                max_install_attempts,
            )
            return result

        # OK — on installe et on retry
        pip_name = AUTO_INSTALL_WHITELIST[missing]
        log.info(
            "Auto-install attempt %d/%d: %r (pip=%r)",
            attempt + 1, max_install_attempts, missing, pip_name,
        )
        install_result = _pip_install(pip_name)
        last_attempted.add(missing)

        if install_result["ok"]:
            installed.append(f"{pip_name} ({install_result['duration_ms']}ms)")
            log.info(
                "Auto-install OK: %r installed in %dms",
                pip_name, install_result["duration_ms"],
            )
            # Boucle pour retry l'exécution
            continue
        else:
            # pip install a raté → on remonte l'erreur enrichie
            log.warning(
                "Auto-install FAILED for %r: %s",
                pip_name, install_result.get("stderr", "")[:200],
            )
            result["stderr"] = (
                result.get("stderr", "")
                + f"\n\n[Lythéa] Tentative d'auto-install de '{pip_name}' "
                f"a échoué : {install_result.get('stderr', 'unknown')[:300]}"
            )
            result["installed_packages"] = list(installed)
            result["install_attempts"] = attempt + 1
            return result

    # On ne devrait jamais atteindre ici, mais filet de sécurité
    return result


def format_result(result: dict, max_stdout_chars: int = 1500) -> str:
    """Format a result dict into a markdown block for the LLM context.

    Used to inject the executor output back into the LLM prompt so it
    can write the final user-facing answer. Truncates stdout if huge.

    V5.9.3 — Le bloc est rendu autoritaire : on dit explicitement au
    LLM que stdout est la source de vérité et qu'il ne doit pas
    recalculer ni inventer d'autres valeurs. Sans ça, Qwen tendait à
    ignorer le résultat exécuté et à halluciner ses propres chiffres,
    surtout en mode two-pass où le grounding web ramène du bruit
    qui pollue le contexte numérique.
    """
    parts: list[str] = []
    if result.get("ok"):
        parts.append(
            f"**Exécution Python réussie** ({result.get('duration_ms', 0)} ms)"
        )
    else:
        parts.append(
            f"**Exécution Python échouée** : `{result.get('error', 'unknown')}`"
        )

    stdout = (result.get("stdout") or "").rstrip()
    if stdout:
        if len(stdout) > max_stdout_chars:
            stdout = stdout[:max_stdout_chars] + "\n...[tronqué]"
        parts.append(
            "**Sortie du programme (source de vérité, à utiliser tel quel) :**\n"
            "```\n" + stdout + "\n```"
        )

    stderr = (result.get("stderr") or "").rstrip()
    if stderr:
        if len(stderr) > max_stdout_chars:
            stderr = stderr[:max_stdout_chars] + "\n...[tronqué]"
        parts.append("Erreurs :\n```\n" + stderr + "\n```")

    plots = result.get("plots") or []
    if plots:
        parts.append(f"({len(plots)} graphique(s) généré(s))")

    # V5.9.3 — Cadrage anti-hallucination pour la réponse finale
    if result.get("ok") and stdout:
        parts.append(
            "**IMPORTANT pour ta réponse finale :**\n"
            "- Utilise les valeurs EXACTES affichées dans la sortie ci-dessus.\n"
            "- Ne recalcule PAS à la main, ne réécris PAS d'approximations.\n"
            "- Si la sortie est `41.5 37.5 24.491`, cite ces chiffres précis.\n"
            "- Tu peux arrondir pour la lecture (`41.5`, `37.5`, `≈ 24.49`) "
            "mais SEULEMENT à partir des chiffres réels affichés ci-dessus, "
            "JAMAIS d'autres valeurs inventées."
        )

    return "\n\n".join(parts)
